# Generated by Django 2.0.6 on 2019-07-05 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '0007_auto_20190705_1006'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_case_name', models.CharField(max_length=200, verbose_name='用例名称')),
                ('web_test_res', models.CharField(max_length=200, verbose_name='测试结果')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.Product', verbose_name='产品')),
                ('web_tester', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='测试人')),
            ],
            options={
                'verbose_name': 'WEB 测试用例',
                'verbose_name_plural': 'WEB 测试用例',
                'db_table': 'WebCase',
            },
        ),
        migrations.CreateModel(
            name='WebCaseStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_case_name', models.CharField(max_length=200, verbose_name='测试用例标题')),
                ('web_test_step', models.CharField(max_length=200, verbose_name='测试步骤')),
                ('web_sbj_name', models.CharField(max_length=200, verbose_name='测试对象描述')),
                ('web_find_method', models.CharField(max_length=200, verbose_name='定位方式')),
                ('web_element', models.CharField(max_length=200, verbose_name='控件元素')),
                ('web_opt_method', models.CharField(max_length=200, verbose_name='操作方法')),
                ('web_test_data', models.CharField(max_length=200, null=True, verbose_name='测试数据')),
                ('web_assert_data', models.CharField(max_length=200, verbose_name='验证数据')),
                ('web_test_res', models.BooleanField(verbose_name='测试结果')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('web_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pro_Web.WebCase', verbose_name='用例名称')),
            ],
            options={
                'verbose_name': 'Web 用例方法步骤',
                'verbose_name_plural': 'Web 用例方法步骤',
                'db_table': 'WebCaseStep',
            },
        ),
    ]
