# Generated by Django 2.0.6 on 2019-07-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pro_Web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webcase',
            name='web_test_res',
            field=models.BooleanField(verbose_name='测试结果'),
        ),
    ]
