# Generated by Django 2.0.6 on 2019-07-03 10:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='文章标题')),
                ('desc', models.CharField(blank=True, max_length=100, verbose_name='文章简介')),
                ('content', mdeditor.fields.MDTextField()),
                ('comment_num', models.IntegerField(default=0, verbose_name='评论数')),
                ('click_num', models.IntegerField(default=0, verbose_name='阅览数')),
                ('love_num', models.IntegerField(default=0, verbose_name='点赞数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '文字表',
                'verbose_name_plural': '文字表',
                'db_table': 'Articles',
                'ordering': ['-add_time'],
            },
        ),
        migrations.CreateModel(
            name='Classify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='文章类别')),
            ],
            options={
                'verbose_name': '文章类别',
                'verbose_name_plural': '文章类别',
                'db_table': 'Classify',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_img', models.ImageField(blank=True, null=True, upload_to='comment_img/%Y/%m/%d/', verbose_name='评论图片')),
                ('comment_content', models.TextField(blank=True, null=True, verbose_name='评论内容')),
                ('comment_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='评论时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Articles.Articles', verbose_name='评论的文章')),
            ],
            options={
                'verbose_name': '文章评论',
                'verbose_name_plural': '文章评论',
                'db_table': 'Comments',
            },
        ),
    ]
