# Generated by Django 2.0.6 on 2019-07-04 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Product', '0005_set'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_case_name', models.CharField(max_length=200, verbose_name='用例名称')),
                ('app_case_result', models.BooleanField(verbose_name='测试结果')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('app_tester', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='测试人')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.Product', verbose_name='产品')),
            ],
            options={
                'verbose_name': 'app 测试用例',
                'verbose_name_plural': 'app 测试用例',
                'db_table': 'APP_Case',
            },
        ),
        migrations.CreateModel(
            name='AppCaseStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_test_step', models.CharField(max_length=200, verbose_name='测试步骤')),
                ('app_sbj_name', models.CharField(max_length=200, verbose_name='测试对象名称描述')),
                ('app_find_method', models.CharField(max_length=200, verbose_name='定位方式')),
                ('app_element', models.CharField(max_length=200, verbose_name='控件元素')),
                ('app_opt_method', models.CharField(max_length=200, verbose_name='操作方法')),
                ('app_test_data', models.CharField(max_length=200, null=True, verbose_name='测试数据')),
                ('app_assert_data', models.CharField(max_length=200, verbose_name='验证数据')),
                ('app_res', models.BooleanField(verbose_name='测试结果')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='添加时间')),
                ('appcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.AppCase', verbose_name='测试用例')),
            ],
            options={
                'verbose_name': 'app 案例测试步骤',
                'verbose_name_plural': 'app 案例测试步骤',
                'db_table': 'AppCaseStep',
            },
        ),
    ]
