# Generated by Django 2.0.6 on 2019-07-05 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_appcase_appcasestep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apitest',
            name='api_tester',
        ),
        migrations.RemoveField(
            model_name='apitest',
            name='product',
        ),
        migrations.RemoveField(
            model_name='apiteststep',
            name='api_test',
        ),
        migrations.RemoveField(
            model_name='appcase',
            name='app_tester',
        ),
        migrations.RemoveField(
            model_name='appcase',
            name='product',
        ),
        migrations.RemoveField(
            model_name='appcasestep',
            name='appcase',
        ),
        migrations.RemoveField(
            model_name='bug',
            name='bug_creater',
        ),
        migrations.RemoveField(
            model_name='bug',
            name='product',
        ),
        migrations.DeleteModel(
            name='Set',
        ),
        migrations.DeleteModel(
            name='ApiTest',
        ),
        migrations.DeleteModel(
            name='ApiTestStep',
        ),
        migrations.DeleteModel(
            name='AppCase',
        ),
        migrations.DeleteModel(
            name='AppCaseStep',
        ),
        migrations.DeleteModel(
            name='Bug',
        ),
    ]
