# Generated by Django 2.0.6 on 2019-07-05 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pro_Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitest',
            name='api_test_res',
            field=models.BooleanField(verbose_name='测试结果'),
        ),
        migrations.AlterField(
            model_name='apiteststep',
            name='api_status',
            field=models.BooleanField(verbose_name='是否通过'),
        ),
    ]
