# Generated by Django 2.0.6 on 2019-07-09 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_auto_20190705_1006'),
        ('Pro_Api', '0002_auto_20190705_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=100, verbose_name='接口名称')),
                ('api_url', models.CharField(max_length=200, verbose_name='url地址')),
                ('api_par_val', models.CharField(max_length=800, verbose_name='请求参数和值')),
                ('api_method', models.CharField(choices=[('get', 'get'), ('post', 'post'), ('put', 'put'), ('delete', 'delete'), ('patch', 'patch')], default='get', max_length=200, verbose_name='请求参数')),
                ('api_result', models.CharField(max_length=200, verbose_name='预期结果')),
                ('api_status', models.BooleanField(verbose_name='是否通过')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.Product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '单一接口接口',
                'verbose_name_plural': '单一接口接口',
                'db_table': 'Apis',
            },
        ),
    ]
