# Generated by Django 2.0.6 on 2019-07-09 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pro_Api', '0003_apis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apis',
            options={'verbose_name': '单一场景接口', 'verbose_name_plural': '单一场景接口'},
        ),
    ]
