# Generated by Django 2.0.6 on 2019-07-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat_eye',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieName', models.CharField(max_length=50, verbose_name='電影名')),
                ('releaseInfo', models.CharField(max_length=10, verbose_name='上映天数')),
                ('sumBoxInfo', models.CharField(max_length=50, verbose_name='綜合票房')),
                ('boxInfo', models.CharField(max_length=50, verbose_name='票房占比')),
                ('boxRate', models.CharField(max_length=50, verbose_name='排片場次')),
                ('avgShowView', models.CharField(max_length=50, verbose_name='人均场次')),
                ('avgSeatView', models.CharField(max_length=50, verbose_name='上座率')),
            ],
            options={
                'db_table': 'cat_eyes',
            },
        ),
        migrations.CreateModel(
            name='QuanJi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=100, verbose_name='电影名')),
                ('m_img', models.CharField(max_length=300, verbose_name='电影图')),
                ('m_url', models.CharField(max_length=400, verbose_name='下载地址')),
                ('m_content', models.CharField(max_length=1000, verbose_name='简介')),
            ],
        ),
    ]
